#!/usr/bin/env node
/* Writes tanis/cards.tex, the printable sheet, from js/facts.js.
 *   node tanis/tools/make_cards.js
 * Eight cards to a US-letter page (two across, four down), in number order so
 * a card is easy to find by its number. The cards butt against each other; cut
 * along the grey lines. Compile with pdflatex. */
'use strict';
const fs = require('fs');
const path = require('path');
const { facts } = require('../js/facts.js');

const tex = (s) => s
  .replace(/\\/g, '\\textbackslash{}')
  .replace(/([%&#$_{}])/g, '\\$1')
  .replace(/~/g, '\\textasciitilde{}')
  .replace(/—/g, '---').replace(/–/g, '--')
  .replace(/“/g, '``').replace(/”/g, "''")
  .replace(/’/g, "'").replace(/°/g, '\\textdegree{}');

const PER_PAGE = 8;

function build() {
  const cards = facts.slice().sort((a, b) => a.n - b.n);
  const cell = (f) => f
    ? `\\factcard{${f.n}}{${tex(f.text)}}`
    : '\\parbox[t][\\cardh][t]{\\cardw}{\\strut}';
  const pages = [];
  for (let i = 0; i < cards.length; i += PER_PAGE) {
    const pg = cards.slice(i, i + PER_PAGE);
    while (pg.length < PER_PAGE) pg.push(null);
    const rows = [];
    for (let r = 0; r < PER_PAGE; r += 2) rows.push(`${cell(pg[r])} & ${cell(pg[r + 1])} \\\\ \\hline`);
    pages.push(`\\begin{tabular}{|@{}c@{}|@{}c@{}|}\\hline\n${rows.join('\n')}\n\\end{tabular}`);
  }
  return `% Generated by tanis/tools/make_cards.js from js/facts.js. Edit the facts there, not here.
\\documentclass[11pt]{article}
\\usepackage[T1]{fontenc}
\\usepackage[default]{sourcesanspro}
\\usepackage[letterpaper,top=0.5in,bottom=0.4in,left=0.25in,right=0.25in,nohead,nofoot]{geometry}
\\usepackage[table]{xcolor}
\\usepackage{array}

\\newlength{\\cardw}\\setlength{\\cardw}{3.95in}
\\newlength{\\cardh}\\setlength{\\cardh}{2.4in}
\\definecolor{cut}{gray}{0.62}
\\definecolor{soft}{gray}{0.35}
\\arrayrulecolor{cut}
\\setlength{\\arrayrulewidth}{0.4pt}
\\setlength{\\tabcolsep}{0pt}
\\pagestyle{empty}
\\setlength{\\parindent}{0pt}

% number, text
\\newcommand{\\factcard}[2]{%
  \\parbox[t][\\cardh][t]{\\cardw}{%
    \\vspace{0.13in}\\hspace{0.18in}%
    \\parbox[t]{\\dimexpr\\cardw-0.36in}{%
      {\\fontsize{34}{34}\\selectfont\\bfseries #1}\\par
      \\vspace{0.07in}%
      {\\raggedright\\fontsize{11}{13.6}\\selectfont #2\\par}%
    }%
  }%
}

\\begin{document}
\\centering
${pages.join('\n\\newpage\n\\centering\n')}
\\end{document}
`;
}

if (require.main === module) {
  const out = path.join(__dirname, '..', 'cards.tex');
  fs.writeFileSync(out, build());
  console.log('wrote ' + out);
}
module.exports = { build };
